### ISSUE TITLE
How to modify the path in VoxCelebData_withmask.py?

### ISSUE THREAD

**Issue by KeyKy** [oawiles/X2Face#11]
what are the differences between landmarks_samevideoimg_125thframe_5imgs.npz and landmarks_samevideoimg_225thframe_5imgs.npz in files.zip?

the follow code in VoxCelebData_withmask.py:
```
# the name here can not match landmarks_samevideoimg_%d25thframe_5imgs in files
files = np.load('/data/files/landmarks_samevideoimg_%d25thframe_5imgs_%d.npz' % (dataset, num_views)) 
```

**Comment by oawiles** [comment]
One is train (landmarks_samevideoimg_125thframe_5imgs) and one is test (landmarks_samevideoimg_225thframe_5imgs). Hope that helps.

**Comment by KeyKy** [comment]
Thanks!
