### ISSUE TITLE
Unclear on how to run training

### ISSUE THREAD

**Issue by wanshun123** [oawiles/X2Face#13]
I have download the train/test splits as follows:

![img1](https://user-images.githubusercontent.com/11178170/50957891-59a6e480-14fa-11e9-8126-b6ad7e0d0296.png)

In `VoxCelebData_withmask.py` I have edited lines 26 and 28 as follows:

```
assert(os.path.exists('/home/paperspace/x2f/x2f/files/landmarks_samevideoimg_%d25thframe_5imgs_%d.npz' % (dataset, num_views)))
files = np.load('/home/paperspace/x2f/x2f/files/landmarks_samevideoimg_%d25thframe_5imgs_%d.npz' % (dataset, num_views))
```

Upon trying to train as follows:

`python3 train_model.py --results_folder '/home/paperspace/x2f/x2f/tensorboard_files' --model_epoch_path '/home/paperspace/x2f/x2f/models'
`

I get the following error (not finding the file):

```
File "/home/paperspace/x2f/x2f/UnwrapMosaic/VoxCelebData_withmask.py", line 26, in __init__
assert(os.path.exists('/home/paperspace/x2f/x2f/files/landmarks_samevideoimg_%d25thframe_5imgs_%d.npz' % (dataset, num_views)))
```

In this case how should the line be edited? I am also a bit confused by line 49 in VoxCelebData_withmask.py:

`img_name = img_name.replace('koepke/voxceleb/faces/', 'ow/voxceleb/faces/faces/')
`

My faces data is download from http://www.robots.ox.ac.uk/~vgg/research/CMBiometrics/data/zippedFaces.tar.gz and looks like the following:

![img2](https://user-images.githubusercontent.com/11178170/50957797-206e7480-14fa-11e9-92f4-2c65b3475529.png)

How should line 49 then be edited?

**Comment by oawiles** [comment]
For the first part it's not finding the file: check the filename and what it is looking for -- something is not the same.

For the second part. The image names were saved with their full path. So you need to find the base part of the filename that is specific to the operating system and replace it with the path you stored. So I think they are at /scratch/local/ssd/koepke/voxceleb/faces but you have the saved at /home/paperspace/x2f/x2f/unzippedFaces. So you need to do something like img_name.replace('/scratch/local/ssd/koepke/voxceleb/faces/', '/home/paperspace/x2f/x2f/unzippedFaces').
