### ISSUE TITLE
Weird results.

### ISSUE THREAD

**Issue by thrillerist** [oawiles/X2Face#15]
Hi Olivia,
I have run the notebooks, and get following output.
The result here is not as good as your demo video. Any idea?
Thanks.

![00](https://user-images.githubusercontent.com/7190154/54871140-da336c80-4dea-11e9-9daf-b882c4a6ce55.png)
![01](https://user-images.githubusercontent.com/7190154/54871142-dacc0300-4dea-11e9-8cd4-8149a694e083.png)
![02](https://user-images.githubusercontent.com/7190154/54871143-dbfd3000-4dea-11e9-85ae-1c5d344ceced.png)

**Comment by oawiles** [comment]
I assume you are just naively running the notebooks.

The problem here is probably a different version of pytorch. In the readme I have listed the version the models were trained in. It is important to use this exact version -- some defaults changed between versions of pytorch meaning that even pretrained models give different results.

As a way to debug, the output should match the images that you see when you first downloaded this github repo (or you can view online on the github repo).

Hope this helps.

**Comment by thrillerist** [comment]
thanks, it works.

**Comment by ghost** [comment]
@oawiles seems !pip install torch==0.2.0 is no longer available 
 Could not find a version that satisfies the requirement torch==0.2.0 (from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0)
No matching distribution found for torch==0.2.0
is there a alternative?

**Comment by oawiles** [comment]
I think you're probably safest trying distributions near that (e.g. 0.3.1, 0.1.2). Then try running the notebook and see if you get the same results as the preloaded results. If you do then great! if not, then that version is not compatible.

**Comment by oawiles** [comment]
Something you could also try (which I haven't) is to change the upsampling (I think the defaults changed with align_corners at some point) which may have been why the pre-computed models don't work properly anymore.

**Comment by ghost** [comment]
@oawiles with torch==0.3.1 I get this error AttributeError: module 'torch' has no attribute 'device' and with 0.1.2 ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-x3n_q9sj/torch/

**Comment by oawiles** [comment]
I'm not sure of installation errors. For the no attribute device : is this in the code? -- you could just edit it.

**Comment by ghost** [comment]
@oawiles I get these results with torch==0.4.1
![Screen Shot 2019-05-11 at 5 08 58 AM](https://user-images.githubusercontent.com/6818285/57567679-fabf8200-73aa-11e9-9536-3f3328591050.png)

**Comment by oawiles** [comment]
Yes this is wrong and I think [this](https://github.com/pytorch/pytorch/pull/5927) is the reason why. So you can try to update the code for upsampling to the old way -- align_corners=True.

**Comment by oawiles** [comment]
(I have not tested this so am not sure but basically you should be able to replicate the defaults in the notebook)

**Comment by ghost** [comment]
@oawiles im still unclear of how I could go about testing this

**Comment by oawiles** [comment]
When you view the notebook on github you should see some default results. When you load in new modules (+ additional changes) you should get the *same* results.

**Comment by mrgloom** [comment]
For macos and python2, after manually fixing code to run models on cpu I was able to reproduce results in 
https://github.com/oawiles/X2Face/blob/master/UnwrapMosaic/Pose2Face.ipynb

```
Python2:
	virtualenv -p /usr/local/bin/python2 x2face_env_py2
	python2 --version
	Python 2.7.15
	pip install https://download.pytorch.org/whl/torch-0.2.0.post3-cp27-none-macosx_10_7_x86_64.whl
	python2 -c "import torch; print(torch.__version__)"
	0.2.0_3
	pip install torchvision==0.2.0 --no-deps --no-cache-dir
	python2 -c "import torchvision; print(torchvision.__version__)"
	0.2.0
	python2 -m pip install ipykernel
	python2 -m ipykernel install --user --name=x2face_env_py2
```

**Comment by tlatlbtle** [comment]
Same issue. I fixed it by install following packages with specific versions:
python=2.7
```
pip2 install https://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl
pip2 install torchvision==0.2.0
```
