### ISSUE TITLE
Confidence factor not exist in origin paper

### ISSUE THREAD

**Issue by davidtranno1** [oawiles/X2Face#19]
Hi @oawiles , many thanks for your great job!
I am wondering the reason why the network in your public paper and the one in your code is not really identical? In concrete, in your paper "X2Face: A network for controlling face generation using images, audio, and pose codes" the embedding network (which is referred in Supplementary Material section) has the output size [2, 256, 256] while in your code the network output is [3, 256, 256]. The additional size (I mean: 3 = _**1**_ + 2) is for confidence (in your source code) but I could not find anything in the origin paper reflect this factor. Could you clarify this? Thank you!

**Comment by oawiles** [comment]
Yes we didn't end up using it. Sorry, we should have taken it out of the code. In the paper we talk about averaging the unwrapped faces? We also considered using confidences but using averaging worked as well if not better so we didn't end up using it in the paper.

**Comment by oawiles** [comment]
In the case of 1 image this confidence has no effect.
