### ISSUE TITLE
Crop Size of Dlib?

### ISSUE THREAD

**Issue by cscyangj** [oawiles/X2Face#2]
Hi, 

It is said that When training the identity, video dataset using dlib to crop the face to 256x256, as i can see from the example image, size is not exactly 256x256.
![image](https://user-images.githubusercontent.com/25877460/46128539-5eef6480-c266-11e8-8088-fdcbffb015b4.png)
![image](https://user-images.githubusercontent.com/25877460/46128560-6e6ead80-c266-11e8-977b-ef35bb3d0c2b.png)

So the reason for adjust image size is for better result or other reasons?

**Comment by oawiles** [comment]
Hi! So we were given the crops and just resized them to 256x256. As you can see it's rarely not square by more than 1/2 pixels.

**Comment by oawiles** [comment]
I'm going to go ahead and close the issue. (We need to resize for training -- the network needs a 256x256 input. otherwise we'd have to pad the image.)
