### ISSUE TITLE
Rotation at zero angle

### ISSUE THREAD

**Issue by mrgloom** [oawiles/X2Face#20]
Generating image with 0,0,0 angle produce different image from input image(assuming that input image is about frontal)

Is it expected behaviour?

Based on https://github.com/oawiles/X2Face/blob/master/UnwrapMosaic/Pose2Face.ipynb
```
# Generate image with zero angle, as a sanity check

values = torch.zeros((1,3))
result = run_batch_pose(source_images + source_images, values[0,:])
result = result.clamp(min=0, max=1)
img = result.squeeze().permute(1,2,0).cpu().data.numpy()

plt.rcParams["figure.figsize"] = [10,10]
plt.subplot(1, 2, 1)
plt.imshow(all_source_images)
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(img)
plt.axis('off')
```

<img width="614" alt="Screenshot 2019-06-14 at 18 10 01" src="https://user-images.githubusercontent.com/4003908/59519047-b0608200-8ecf-11e9-9955-471d7f24a02b.png">

**Comment by akoepke** [comment]
We have observed a similar behaviour which is probably caused by the way we trained this setup resulting in the input angles having a slight offset.
