### ISSUE TITLE
Error occur when training with num_views > 2

### ISSUE THREAD

**Issue by davidtranno1** [oawiles/X2Face#21]
Hi @oawiles ,
The errors occurred when I train the model with num_views greater than 2 due to the provided train/test splitting only for two view (one for source image and one for driving image). The origin paper only refer the Single source and Multi-source at testing time. It is unclear for me the model quality discrepancy between training with Single vs Multi-source?

If the model yielded from training with Multi-source is better, could you suggest me a strategy (e.g heuristic) to create training data?

Thank you!

**Comment by oawiles** [comment]
We didn't find that using multiple views improved results. Hence we didn't put it in the paper. We also haven't tested this part of the code so there may be errors when you try to run it.
