### ISSUE TITLE
torchvision

### ISSUE THREAD

**Issue by melih-unsal** [oawiles/X2Face#23]
How did you use pytorch version older than 1.1 although torchvision requires newer versions?

**Comment by oawiles** [comment]
I trained this a long time ago and have not retrained. If you want to use a newer version you could compare intermediary results to find which layers have changed and then try to reset defaults to make them the same.

**Comment by akoepke** [comment]
You can find an updated version of the demo notebooks and installation instructions to support pytorch 0.4.1 in the ‘pytorch_0.4.1’ branch. This works with torchvision 0.2.1.
