### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by melih-unsal** [oawiles/X2Face#24]
Is it normal that when I downgrade the version of pytorch, it slows down. Normally I can run the notebook code in roughly 4 seconds but after I changed the version, I could run the code in around 10 minutes.

**Comment by BaldrLector** [comment]
@melih1996 Me too, it seems model create takes more time at early version PyTorch. Besides, I find PyTorch 0.2.0 have problem with GPU memory manage, even you detach Variable, this part memory may not be released.

**Comment by oawiles** [comment]
This is probably true. Unfortunately I have not (and probably will not) have time to retrain on the new/better versions. You could compare different version results (to see why results differ) by looking at intermediary results at each layer and verifying they are the same.

**Comment by akoepke** [comment]
You can find an updated version of the demo notebooks and installation instructions to support pytorch 0.4.1 in the ‘pytorch_0.4.1’ branch. Let us know if you still experience these problems.
