### ISSUE TITLE
test result is very bad

### ISSUE THREAD

**Issue by primejava** [oawiles/X2Face#26]

**Comment by oawiles** [comment]
This isn't very helpful. Have you verified you can recreate the default results in the notebooks. Many people have had problems with different torch versions.

**Comment by primejava** [comment]
too many bugs in your code,Why do you want to upload this project to waste ours time?

**Comment by akoepke** [comment]
You can find an updated version of the demo notebooks and installation instructions to support pytorch 0.4.1 in the ‘pytorch_0.4.1’ branch. Let us know if you are still not able to get the demo notebooks running.
