### ISSUE TITLE
About the train code.

### ISSUE THREAD

**Issue by JianxiangWang** [oawiles/X2Face#3]
Hi, This work is amazing and I have run the code.  Could you release the train code?

Thanks a lot!

**Comment by oawiles** [comment]
We will try to do this as soon as we can.

**Comment by JianxiangWang** [comment]
Thank you ~

Olivia <notifications@github.com> 于2018年10月9日周二 下午8:00写道：

**Comment by oawiles** [comment]
I have uploaded sample training code.
