### ISSUE TITLE
The Pose2Face result is different for official demo.

### ISSUE THREAD

**Issue by Fengdalu** [oawiles/X2Face#30]
Hi,

I try to run the Pose2Face demo in this project with pretrained model loaded. The result seems wrong. Is there any advice about reproducing the result? My torch version is 1.0 with python3.

![Taylor_pose](https://user-images.githubusercontent.com/8428800/71162465-3a761280-2286-11ea-8452-a4b6d3769383.jpg)

**Comment by akoepke** [comment]
If you want to use python 3.7, follow the instructions in the py37_pytorch_0.4.1 branch. You will need pytorch 0.4.1 for that.

**Comment by Fengdalu** [comment]
> If you want to use python 3.7, follow the instructions in the py37_pytorch_0.4.1 branch. You will need pytorch 0.4.1 for that.

Thanks.
