### ISSUE TITLE
how to train with my own datasets?

### ISSUE THREAD

**Issue by visonpon** [oawiles/X2Face#7]
Hi, thanks for releasing this wonderful work. I'd like to know how to train with my own datasets~
Hope I can receive your response soon~
thanks~

**Comment by oawiles** [comment]
Hi, We haven't explicitly allowed for this but it should be simple. You should just need to write your own data loader modelled on the VoxCeleb one (so it should return the same order of output) and then load this as opposed to the VoxCeleb in training.
Hope that helps.
