### ISSUE TITLE
What is the python version of release_models(i.e. x2face_model.pth)?

### ISSUE THREAD

**Issue by YimingWei** [oawiles/X2Face#8]
Hi, thanks for releasing this excellent work.
I tried to load pre-trained models as your demo file demonstrated, but a problem arised. The .pth files cannot be loaded. Did you train the model in python2.7 and save it in 2.7? But your code is in python3. I'm confused.

**Comment by oawiles** [comment]
I believe that they were written in python2.7. 

If you're referring to the training code for python3 -- this was a refactored version written later so that would be why there is a change in versions.

**Comment by YimingWei** [comment]
I have tried py27 for pre-trained models. It works! Thank you!

**Comment by mrgloom** [comment]
Seems this error related:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 0: ordinal not in range(128)`

https://discuss.pytorch.org/t/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-918-ordinal-not-in-range-128/15356/6
